services:
  productservice:
    build: .
    ports:
      - "3016:3016"
    environment:
      - ASPNETCORE_URLS=http://+:3016
      - DB_USER=sa
      - DB_PASSWORD=Your_password123
      - DB_SERVER=mssql
      - DB_DATABASE=tradeportdb
    networks:
      - my_network
    volumes:
      - "C:/wwwroot/uploads/images:/app/wwwroot/uploads/images" # Corrected volume path for Windows
networks:
  my_network:
    external: true
