services:
  tradeport-backend-productservice:
    build: ./tradeport-backend-productservice
    ports:
      - "3016:3016"
    environment:
      - ASPNETCORE_URLS=http://+:3016
      - DB_USER=sa
      - DB_PASSWORD=Your_password123
      - DB_SERVER=mssql
      - DB_DATABASE=tradeportdb
  
  
